server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8080/eureka/}
  instance:
    instance-id: front-${random.uuid}

spring:
  application:
    name: front
  jpa:
    defer-datasource-initialization: true
